version: "3.3"

services:

mysqldb:

image: mysql:5.7

restart: unless-stopped

env_file: ./.env

environment:

- MYSQL_ROOT_PASSWORD=root

- MYSQL_DATABASE=achatproject

ports:

- 3306:3306

volumes:

- './.mysql-data/db:/var/lib/mysql'

app:

depends_on:

- mysqldb

image: bader123/achatproject:40

restart: on-failure

env_file: ./.env

ports:

- 8089:8089

environment:

SPRING_APPLICATION_JSON: '{

"spring.datasource.url" : "jdbc:mysql://mysqldb:3306/achatproject?useSSL=false",

"spring.datasource.username" : "root",

"spring.datasource.password" : "root",

"spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",

"spring.jpa.hibernate.ddl-auto" : "update"}'